FROM php:7.2-apache
LABEL maintainer="ono.naoyaa@gmail.com"

# Install the required packages and remove the apt cache.
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    git \
    zip \
    unzip \
  && rm -rf /var/lib/apt/lists

RUN apt-get -y update \
&& apt-get install -y libicu-dev \
&& docker-php-ext-configure intl \
&& docker-php-ext-install intl

RUN apt-get install -y libzip-dev

RUN docker-php-ext-install zip

RUN apt-get update -y && apt-get install -y sendmail libpng-dev

RUN docker-php-ext-install gd
# Enable PHP extensions
RUN docker-php-ext-install pdo_mysql mysqli
# Install curl  prerequisites
RUN apt-get update && apt-get install -y curl
# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

# Add cake command to system path
ENV PATH="${PATH}:/var/www/html/lib/Cake/Console"
ENV PATH="${PATH}:/var/www/html/Vendor/bin"

# COPY site conf file
COPY ./php/apache/site.conf /etc/apache2/sites-available/000-default.conf

# Copy the code into /var/www/html/ inside the image
COPY . .

# Set default working directory
WORKDIR ./

# Create tmp directory and make it writable by the web server
RUN mkdir -p \
    tmp/cache/models \
    tmp/cache/persistent \
  && chown -R :www-data \
    tmp \
  && chmod -R 770 \
    tmp
COPY ./arch/scripts/start.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/start.sh
# Enable Apache modules and restart
RUN a2enmod rewrite \
  && service apache2 restart

EXPOSE 80

CMD ["start.sh"]