version: '3'
services:
    doubble:
        image: d4_php
        volumes:
            - ./:/var/www/html
            - ./logs/apache/blogs:/var/log/apache2
        ports: 
            - '8020:80'
        environment: 
            - VIRTUAL_HOST=bloged.com
        networks: 
            - d4_default    
networks: 
    d4_default: 
        external: 
            name: d4_default
